package com.thehorselegend.summs.domain.vehicle;

public class VehicleFactory {

    // A VehicleFactory is a utility class with static methods 
    // to create different types of vehicles.
    // ID will be generated by persistence layer; hence, it's set to null by default.

    public static Bicycle createBicycle(
            Location location,
            Long providerId,
            Double costPerMinute) {
        return new Bicycle(
                null,  
                VehicleStatus.AVAILABLE,
                location,
                providerId,
                costPerMinute
        );
    }

    public static Scooter createScooter(
            Location location,
            Long providerId,
            Double costPerMinute,
            Double maxRange) {
        return new Scooter(
                null,  
                VehicleStatus.AVAILABLE,
                location,
                providerId,
                costPerMinute,
                maxRange
        );
    }
    
    public static Car createCar(
            Location location,
            Long providerId,
            Double costPerMinute,
            String licensePlate,
            Integer seatingCapacity) {
        return new Car(
                null,  
                VehicleStatus.AVAILABLE,
                location,
                providerId,
                costPerMinute,
                licensePlate,
                seatingCapacity
        );
    }
}
